services:
  client:
    build:
      context: .
      dockerfile: dockerfile-client
    image: seunggwan/corinee-client
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
