services:
  server:
    image: seunggwan/corinee-server
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge